### ISSUE TITLE
i can only detect one face.

### ISSUE THREAD

**Issue by ffffwyy** [SyGoing/LFFD-with-ncnn#1]
my picture have many faces,while the code can only find one ,why?

**Comment by SyGoing** [comment]
sometimes it is,I just implement it , maybe you can test the official python code and issue .

**Comment by SyGoing** [comment]
And , you can try the another model ,set scale_num=8

**Comment by SyGoing** [comment]
Hello ,@fanwenyang, my code has some bug ,I will fix it;
