### ISSUE TITLE
Model Conversion

### ISSUE THREAD

**Issue by gwestner94** [SyGoing/LFFD-with-ncnn#2]
Hi,

thank you for your contribution.
Could you tell me how you converted the Mxnet model to NCNN?
When I tried the direct conversion using the Mxnet2Ncnn tool, there are layers missing.
Did you convert it to ONNX first?
Would be great if you could share a conversion path.

Thank you!

**Comment by SyGoing** [comment]
Hello @gwestner94 , I have a MNN implementation ，in that readme , I have give the solutions to convert the original model : https://github.com/SyGoing/LFFD-MNN.  In fact, if you modify the symbol, you can convert it successfully! Hope it can help you

**Comment by gwestner94** [comment]
Thank you! Works for me :)
