### ISSUE TITLE
detection result is wrong with converted model(v2)

### ISSUE THREAD

**Issue by ForestWang** [SyGoing/LFFD-with-ncnn#6]
the bounding box is large and missed most of the faces in the image.

**Comment by SyGoing** [comment]
the model you used is converted by you ? could you please give your image?

**Comment by ForestWang** [comment]
![test1](https://user-images.githubusercontent.com/5412083/66804595-71ae0780-ef55-11e9-90d7-16d384c2b5ce.jpg)

**Comment by SyGoing** [comment]
@ForestWang ，Hi ，I have test the image with the original v2 model(update by the author) ,there is no wrong detection ，please check it again

**Comment by ForestWang** [comment]
yes, with the mxnet python demo, the result is right. I mean the result is wrong with your ncnn project.

**Comment by SyGoing** [comment]
OK, thanks  , I will test it right now

**Comment by SyGoing** [comment]
Hello ,@ForestWang,  I have test and debug it, the problem is my test code, I will update it right now,  Thanks very much

**Comment by SyGoing** [comment]
Hello ,@ForestWang,  I have test and debug it, the problem is my test code, I will update it right now,  Thanks very much

**Comment by SyGoing** [comment]
I have fixed it
